// <auto-generated />
namespace HackathonTeamBuilder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removeteamidkeyteammodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeteamidkeyteammodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202402090126360_remove-team-id-key-team-model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
